<?php

namespace Container3hlOgr3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtKelMfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VtKelMf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VtKelMf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'profil' => ['privates', '.errored..service_locator.VtKelMf.App\\Entity\\Profil', NULL, 'Cannot autowire service ".service_locator.VtKelMf": it needs an instance of "App\\Entity\\Profil" but this type has been excluded in "config/services.yaml".'],
            'profilRepository' => ['privates', 'App\\Repository\\ProfilRepository', 'getProfilRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'profil' => 'App\\Entity\\Profil',
            'profilRepository' => 'App\\Repository\\ProfilRepository',
            'slugger' => '?',
            'tokenStorage' => '?',
        ]);
    }
}
