<?php

namespace Container3hlOgr3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZpOVPfdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zpOVPfd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zpOVPfd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offer' => ['privates', '.errored..service_locator.zpOVPfd.App\\Entity\\Offer', NULL, 'Cannot autowire service ".service_locator.zpOVPfd": it needs an instance of "App\\Entity\\Offer" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'offer' => 'App\\Entity\\Offer',
            'slugger' => '?',
        ]);
    }
}
