<?php

namespace Container3hlOgr3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PsADFpYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.psADFpY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.psADFpY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'offer' => ['privates', '.errored..service_locator.psADFpY.App\\Entity\\Offer', NULL, 'Cannot autowire service ".service_locator.psADFpY": it needs an instance of "App\\Entity\\Offer" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'offer' => 'App\\Entity\\Offer',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
