<?php

namespace ContainerLrxx0Lj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SDzmTsBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SDzmTsB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SDzmTsB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'offerRepository' => ['privates', 'App\\Repository\\OfferRepository', 'getOfferRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'offerRepository' => 'App\\Repository\\OfferRepository',
            'slugger' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
