<?php

namespace ContainerLrxx0Lj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R3nDK7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R3nDK_7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R3nDK_7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'company' => ['privates', '.errored..service_locator.R3nDK_7.App\\Entity\\Company', NULL, 'Cannot autowire service ".service_locator.R3nDK_7": it needs an instance of "App\\Entity\\Company" but this type has been excluded in "config/services.yaml".'],
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'company' => 'App\\Entity\\Company',
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'slugger' => '?',
        ]);
    }
}
