<?php

namespace ContainerLrxx0Lj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompany1TypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Company1Type' shared autowired service.
     *
     * @return \App\Form\Company1Type
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Company1Type.php';

        return $container->privates['App\\Form\\Company1Type'] = new \App\Form\Company1Type();
    }
}
