<?php

namespace ContainerLrxx0Lj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffer2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.psADFpY.App\Entity\Offer' shared service.
     *
     * @return \App\Entity\Offer
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.psADFpY": it needs an instance of "App\\Entity\\Offer" but this type has been excluded in "config/services.yaml".');
    }
}
