<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrxx0Lj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrxx0Lj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrxx0Lj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrxx0Lj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLrxx0Lj\App_KernelDevDebugContainer([
    'container.build_hash' => 'Lrxx0Lj',
    'container.build_id' => 'd1a529fa',
    'container.build_time' => 1689760166,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrxx0Lj');
